flight_details = {
  "plane_details":
{"plane_type":"Airbus A380-800",
"Company":"KLM",
"destinations":["Nairobi", "London", "Kuala Lumpur", "Amsterdam", "Toronto"],
"capacity":20,
"flight_status":"interntational"},
{"plane_type":"Boeing 747-8",
"Company":"Qatar Airways",
"destinations":["Luxembourg", "London", "Denmark", "Amsterdam", "Toronto"],
"capacity":20,
"flight_status":"interntational"},
{"plane_type":"Boeing 747-400",
"Company":"Ethiopia Airways",
"destinations":["Ottawa", "Sofia", "Vienna", "Beijing", "Toronto"],
"capacity":20,
"flight_status":"interntational"},
{"plane_type":"Boeing 777-300",
"Company":"Airlink",
"destinations":["New Delhi", "London", "Libreville", "Helsinki", "Toronto"],
"capacity":20,
"flight_status":"interntational"},
{"plane_type":"Airbus A340-600",
"Company":"Eritrea Airways",
"destinations":["Havana", "Tokyo", "Djibouti", "Amsterdam", "Paris"],
"capacity":20,
"flight_status":"interntational"},
{"plane_type":"Boeing 777-200",
"Company":"FLY-SAX",
"destinations":["Nairobi", "London", "Kuala Lumpur", "Amsterdam", "Toronto"],
"capacity":20,
"flight_status":"interntational"},
{"plane_type":"Airbus A350-900",
"Company":"Silverstone",
"destinations":["Nairobi", "London", "Kuala Lumpur", "Amsterdam", "Toronto"],
"capacity":20,
"flight_status":"interntational"},
{"plane_type":"Airbus A340-500",
"Company":"Jambojet",
"destinations":["Nairobi", "Kisumu", "Busia", "Siaya", "Maseno"],
"capacity":20,
"flight_status":"local"},
{"plane_type":"Airbus A333-300"
"Company":"FLY540",
"destinations":["Nairobi", "Mombasa", "Kakamega", "Kilifi", "Diani"],
"capacity":20,
"flight_status":"local"},
{"plane_type":"Airbus A340-300",
"Company":"Kenya Airways",
"destinations":["Seattle", "New york", "Johanesburg", "Lagos", "Dar Es Salaam"],
"capacity":20,
"flight_status":"interntational"}
}
